name: update
inputs:
  package_name:
    description: "package name"
    required: true
  github_token:
    description: "github token"
    required: true
runs:
  using: "composite"
  steps:
    - name: update
      working-directory: apps/${{ inputs.package_name }}
      run: ./update.ps1
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_ACTIONS_RUNNER_TLS_NO_VERIFY: "1"
      shell: powershell
    - name: diff check
      working-directory: apps/${{ inputs.package_name }}
      run: | 
        $result = &git diff --name-only --relative=apps/${{ inputs.package_name }}
        if( -not ([string]::IsNullOrEmpty($result)) ) {
          chocolatey pack
          chocolatey install ${{ inputs.package_name }} -s . -y
          chocolatey push
        } else { 
          echo "no push" 
          echo "no push2"
        }
      shell: powershell
    - name: test2
      working-directory: apps/${{ inputs.package_name }}
      run: echo "aaaaa" >> ./ReadMe.md
      shell: powershell
    - name: test
      working-directory: apps/${{ inputs.package_name }}
      run: $result = &git diff --name-only --relative=apps/${{ inputs.package_name }}
      shell: powershell
    - name: test4
      working-directory: apps/${{ inputs.package_name }}
      run: echo $result
      shell: powershell
    - name: test3
      working-directory: apps/${{ inputs.package_name }}
      run: |
        if( -not ([string]::IsNullOrEmpty($result)) ) { echo "test" } 
        else { echo "test2" }
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_ACTIONS_RUNNER_TLS_NO_VERIFY: "1"
      shell: powershell
