name: push awssamcli
on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  push-awssamcli:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - working-directory: apps/awssamcli
        run: | 
          chocolatey apikey --key ${{ secrets.CHOCOLATEY_APIKEY }} --source https://push.chocolatey.org/
          chocolatey pack
          chocolatey push
