name: push nyagos
on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  push-nyagos:
    runs-on: windows-latest
    steps:
      - working-directory: apps/nyagos
        run: | 
          chocolatey apikey --key ${{ secrets.CHOCOLATEY_APIKEY }} --source https://push.chocolatey.org/
          chocolatey pack
          chocolatey push
